package javaexceptions;

public class caughtexception {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("begining !!");
		int i[]= new int [2];
		 i[5]=100;
		System.out.println("Ending!!");
	}

}
